### ISSUE TITLE
Any plans to add a release supported via console?

### ISSUE THREAD

**Issue by uhlhosting** [ShiKaiWi/mattermost-coderunner-plugin#1]

**Comment by ShiKaiWi** [comment]
@uhlhosting Could you give an explanation for **supported via console**?

**Comment by uhlhosting** [comment]
Meaning about these steps:
- Log in to Mattermost as a System Admin.
- Open the System Console at `/admin_console`
- Navigate to **Plugins (Beta) > Management** and upload the `plugin.tar.gz` you generated above.
- Click **Enable** under the plugin after it has uploaded.

**Comment by ShiKaiWi** [comment]
> Meaning about these steps:
> 
> * Log in to Mattermost as a System Admin.
> * Open the System Console at `/admin_console`
> * Navigate to **Plugins (Beta) > Management** and upload the `plugin.tar.gz` you generated above.
> * Click **Enable** under the plugin after it has uploaded.

Sounds great!
I will do some investigation at this weekend.

**Comment by woshixixi** [comment]
> Meaning about these steps:
> 
> * Log in to Mattermost as a System Admin.
> * Open the System Console at `/admin_console`
> * Navigate to **Plugins (Beta) > Management** and upload the `plugin.tar.gz` you generated above.
> * Click **Enable** under the plugin after it has uploaded.

Hi, about how to install plugin please see here: https://developers.mattermost.com/extend/plugins/server/hello-world/#installing-the-plugin

I don't quite understand why we should add a release to support installing our plugin ?

**Comment by ShiKaiWi** [comment]
> > Meaning about these steps:
> > 
> > * Log in to Mattermost as a System Admin.
> > * Open the System Console at `/admin_console`
> > * Navigate to **Plugins (Beta) > Management** and upload the `plugin.tar.gz` you generated above.
> > * Click **Enable** under the plugin after it has uploaded.
> 
> Hi, about how to install plugin please see here: https://developers.mattermost.com/extend/plugins/server/hello-world/#installing-the-plugin
> 
> I don't quite understand why we should add a release to support installing our plugin ?

Close because it seems just a normal procedure to install a plugin.

**Comment by uhlhosting** [comment]
I do not find an official tar.gz release of this plugin. Like any other mm plugin have on github. check yourself!

**Comment by ShiKaiWi** [comment]
> I do not find an official tar.gz release of this plugin. Like any other mm plugin have on github. check yourself!

I'm sorry to misunderstand you and actually a script in this repo has been provided to build the whole plugin. Anyway I will create a such tar.gz release of this.
